export const products = [
    {
        "id": 1,
        "nombre": 'Arroz',
        "descripcion": "Comida",
        "price": 100,
        "thumbnail": "sinimagen",
        "code": "A123",
        "stock": 45,
    },

    {
        "id": 2,
        "nombre": 'Fideos',
        "descripcion": "Comida",
        "price": 200,
        "thumbnail": "sinimagen",
        "code": "F123",
        "stock": 15,
    },

    {
        "id":3,
        "nombre": 'Queso',
        "descripcion": "Comida",
        "price": 300,
        "thumbnail": "sinimagen",
        "code": "Q123",
        "stock": 10,
    },

    {
        "id":4,
        "nombre": 'Huevos',
        "descripcion": "Comida",
        "price": 400,
        "thumbnail": "sinimagen",
        "code": "H123",
        "stock": 40,
    },
    {
        "id":5,
        "nombre": 'Porotos',
        "descripcion": "Comida",
        "price": 500,
        "thumbnail": "sinimagen",
        "code": "P123",
        "stock": 30,
    },
    {
        "id":6,
        "nombre": 'Lata de choclo',
        "descripcion": "Comida",
        "price": 600,
        "thumbnail": "sinimagen",
        "code": "CH123",
        "stock": 20,
    },
    {
        "id":7,
        "nombre": 'Lata de atún',
        "descripcion": "Comida",
        "price": 700,
        "thumbnail": "sinimagen",
        "code": "AT123",
        "stock": 10,
    },
    {
        "id":8,
        "nombre": 'Servilletas',
        "descripcion": "No es comida",
        "price": 800,
        "thumbnail": "sinimagen",
        "code": "S123",
        "stock": 20,
    },
    {
        "id":9,
        "nombre": 'Gaseosa',
        "descripcion": "Bebida",
        "price": 900,
        "thumbnail": "sinimagen",
        "code": "G123",
        "stock": 50,
    },
    {
        "id":10,
        "nombre": 'Bidón de agua',
        "descripcion": "Bebida",
        "price": 1000,
        "thumbnail": "sinimagen",
        "code": "BA123",
        "stock": 90,
    }
    
]